CREATE DATABASE auth_db WITH OWNER='postgres' ENCODING = 'UTF8';
CREATE DATABASE security WITH OWNER='postgres' ENCODING = 'UTF8';
CREATE DATABASE globals WITH OWNER='postgres' ENCODING = 'UTF8';
CREATE DATABASE invoicing WITH OWNER='postgres' ENCODING = 'UTF8';
